# Generated by Django 4.2.3 on 2023-08-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acess',
            name='email',
            field=models.CharField(default='dvs@gmail.com', max_length=100),
        ),
    ]
